version: "2.4"
services:
  game:
    build:
      context: .
      dockerfile: Dockerfile
    image: five-against-five:local
    container_name: five-against-five
    ports:
      - "43127:43127"
    environment:
      - NODE_ENV=production
      - PORT=43127
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    volumes:
      - ./data:/app/data:ro
      - ./.data:/app/.data
